spring:
  application:
    name: file-upload
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
      file-size-threshold: 10MB
  mvc:
    async:
      request-timeout: 1h

aws:
  s3:
    endpoint: http://localhost:4566
    region: us-east-1
    access-key: test
    secret-key: test
    bucket: bsejawal
    folder: uploads
    path-style-access: true
