create table if not exists "account" (
    id bigint generated by default as identity primary key,
    account_no varchar(50) not null,
    pal_account varchar(50),
    name varchar(255),
    address varchar(255),
    city varchar(100),
    state varchar(100),
    constraint uk_account_account_no unique (account_no)
);

create table if not exists "position" (
    id bigint generated by default as identity primary key,
    account_no varchar(50) not null,
    stock varchar(20) not null,
    "value" decimal(19, 2) not null,
    constraint fk_position_account_no foreign key (account_no) references "account" (account_no)
);
